include:
  - project: gazprom-asez/pipelines
    ref: main
    file: python/flake8.yaml
stages:
  - lint
  - build
  - test
  - upload
build:
  stage: build
  tags:
    - dev-runner
  script:
    - pip install twine poetry
    - pip install -r requirements.txt
    #- poetry build
    - python3 -m build
    - ls -lah
    - ls -lah dist
    - |
      cat <<EOT >> .pypirc
      [distutils]
      index-servers =
          rabbitmq-broker
      [rabbitmq-broker]
          repository: https://pypi.org/
          username: ${PYPI_USERNAME}
          password: ${PYPI_PASSWORD}
      EOT
    - cat .pypirc
    - python -m twine upload --repository rabbitmq-broker dist/rabbitmq_broker-${CI_COMMIT_TAG}-py3-none-any.whl --config-file .pypirc
  only:
    - tags

