include:
  - project: gazprom-asez/pipelines
    ref: main
    file: python/flake8.yaml
stages:
  - lint
  - build
  - test
  - upload
build:
  stage: build
  tags:
    - dev-runner
  script:
    - pip install twine poetry
    - pip install -r requirements.txt
    #- poetry build
    - python3 -m build
    - ls -lah
    - ls -lah dist
