include:
  - project: gazprom-asez/pipelines
    ref: main
    file: python/flake8.yaml
stages:
  - lint
  - build
  - upload
build:
  stage: build
  tags:
    - dev-runner
  script:
    - pip install twine poetry
    - pip install -r requirements.txt
    # Замена версии в файле pyproject.toml
    - sed -i '/version/s/".*"/"'${CI_COMMIT_TAG}'"/' pyproject.toml
    - python -m build
    - ls -lah
    - ls -lah dist
    # Формируем файл .pypirc со сведениями для загрузки проекта на https://pypi.org/manage/project/rabbitmq-broker/releases/
    - |
      cat <<EOT >> .pypirc
      [distutils]
      index-servers =
          rabbitmq-broker
      [rabbitmq-broker]
          repository: https://upload.pypi.org/legacy/
          username: ${PYPI_USERNAME}
          password: ${PYPI_PASSWORD}
      EOT
    - cat .pypirc
    # https://medium.com/maisonsdumonde/gitlab-ci-cd-and-gitlab-pypi-repository-4916a51d22eb
    # https://docs.gitlab.com/ee/user/packages/pypi_repository/
    # https://twine.readthedocs.io/en/stable/
    - python -m twine upload --repository rabbitmq-broker dist/rabbitmq_broker-${CI_COMMIT_TAG}-py3-none-any.whl --config-file .pypirc
  only:
    - tags
